### ISSUE TITLE
function 'PhaSpaRecon' can not be found

### ISSUE THREAD

**Issue by HuazeTang** [wt1234wt/FRMM-framework#1]
Hello! I am running this wonderful project on predicting observations in complex system with FRMM. However, it seems that function 'PhaSpaRecon' is not included. I have no idea where I can find this function or it is juat a build-in function for matlab. I hope you can help me on this issue. Thank you for your reply!

**Comment by Viromic** [comment]
PhaSpaRecon is or used to be a matlab function 

% Phase space reconstruction
tau = 2;
m = 9;
xn = PhaSpaRecon(x,tau,m);              % Each column and one point
N = size(xn,2);                         % Number of phase space points

function [xn,dn] = PhaSpaRecon(s,tau,m,T)
% Phase space reconstruction of chaotic sequence (phase space reconstruction)
% [xn, dn, xn_cols] = PhaSpaRecon(s, tau, m)
 % Input parameters: s chaotic sequence (column vector)
 % tau reconstruction delay
 % m reconstruction dimension
 % T directly predict the number of steps
 % Output parameter: xn point sequence in phase space (each column is a point)
 % dn one-step prediction target (row vector)

[rows,cols] = size(s);
if (rows>cols)
    len = rows;
    s = s';
else
    len = cols;
end

if (nargin < 4)
    T = 1;
end

if (nargout==1)

    if (len-(m-1)*tau < 1)
        disp('err: delay time or the embedding dimension is too large!')
        xn = [];
    else
        xn = zeros(m,len-(m-1)*tau);
        for i = 1:m
                         xn(i,:) = s(1+(i-1)*tau: len-(m-i)*tau);% phase space reconstruction, each line is a point 
        end
    end
    
elseif (nargout==2)
    
    if (len-T-(m-1)*tau < 1)
        disp('err: delay time or the embedding dimension is too large!')
        xn = [];
        dn = [];
    else
        xn = zeros(m,len-T-(m-1)*tau);
        for i = 1:m
                         xn(i,:) = s(1+(i-1)*tau: len-T-(m-i)*tau);% phase space reconstruction, each line is a point 
        end
                 dn = s(1+T+(m-1)*tau: end);% predicted target
    end
    
end





function [xn,dn] = PhaSpaRecon(s,tau,m,T)

[rows,cols] = size(s);
if (rows>cols)
    len = rows;
    s = s';
else
    len = cols;
end

if (nargin < 4)
    T = 1;
end

if (nargout==1)

    if (len-(m-1)*tau < 1)
        disp('err: delay time or the embedding dimension is too large!')
        xn = [];
    else
        xn = zeros(m,len-(m-1)*tau);
        for i = 1:m
            xn(i,:) = s(1+(i-1)*tau : len-(m-i)*tau);  
        end
    end
    
elseif (nargout==2)
    
    if (len-T-(m-1)*tau < 1)
        disp('err: delay time or the embedding dimension is too large!')
        xn = [];
        dn = [];
    else
        xn = zeros(m,len-T-(m-1)*tau);
        for i = 1:m
            xn(i,:) = s(1+(i-1)*tau : len-T-(m-i)*tau);  
        end
        dn = s(1+T+(m-1)*tau : end);    
    end
    
end
